// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBodoJrWf55fpY3dMHUU8f_ULcCEGbrhok',
    appId: '1:10363432334:web:7e87959723cd8a23c588df',
    messagingSenderId: '10363432334',
    projectId: 'flutter-chat-app-c5335',
    authDomain: 'flutter-chat-app-c5335.firebaseapp.com',
    storageBucket: 'flutter-chat-app-c5335.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8sxuOtX5t74nUO5DdvpCwDWKf9cHK0Ds',
    appId: '1:10363432334:android:df422eecf05dd858c588df',
    messagingSenderId: '10363432334',
    projectId: 'flutter-chat-app-c5335',
    storageBucket: 'flutter-chat-app-c5335.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgrv3oCNhFePNAD033MJhuhaMxB61P0IY',
    appId: '1:10363432334:ios:73225d2293756f48c588df',
    messagingSenderId: '10363432334',
    projectId: 'flutter-chat-app-c5335',
    storageBucket: 'flutter-chat-app-c5335.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
